### ISSUE TITLE
product.go と product_test.go に必要なライブラリ

### ISSUE THREAD

**Issue by sogaoh** [sogaoh/sam-book-sample#3]
- 47 ページの `models/product_test.go` に必要なライブラリが記載されていない。  
勘とIDEのサポートで以下にした。
```
import (
	"sam-book-sample/db"

	"fmt"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/guregu/dynamo"
)
```

- 44  ページの `models/product.go` に必要なライブラリが足りてない。  
勘とIDEのサポートで以下にした。
```
import (
	"sam-book-sample/db"
	"github.com/memememomo/nomof"  //追加

	"time"

	"github.com/pkg/errors"        //追加
	"github.com/guregu/dynamo"     //追加
)
```

**Comment by memememomo** [comment]
https://github.com/memememomo/sam-book-sample/blob/master/README.md#%E5%BF%85%E8%A6%81%E3%81%AA%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E3%82%A4%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%88

ご報告ありがとうございました。
README.md に正誤表で追記いたしました 🙇 
PDF版も修正する予定です。
