### ISSUE TITLE
最後まで実装したのだが make deploy が失敗する（Error 255）

### ISSUE THREAD

**Issue by sogaoh** [sogaoh/sam-book-sample#5]
最終的に、[deploy] Error 255 になってしまう。。

- 255 って何なのか？
- deploy 前に問題をどう検知すればよいのか？

```
~/src/temp/20190501/sam-book-sample practice-sogaoh
❯ make deploy
・・・
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run sam-local ./scripts/deploy.sh
upload: ./swagger.yml to s3://swagger-xxxxxxxxxxxxxxxxxxxx/swagger.yml
Uploading to 6c0cc73f836112c460a7f62497db826e  4307027 / 4307027.0  (100.00%)
Successfully packaged artifacts and wrote output template to file ./packaged.yml.
Execute the following command to deploy the packaged template
aws cloudformation deploy --template-file /var/opt/src/sam-book-sample/packaged.yml --stack-name <YOUR STACK NAME>

Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
aws cloudformation describe-stack-events --stack-name sam-sample
make: *** [deploy] Error 255

~/src/temp/20190501/sam-book-sample practice-sogaoh 6m 40s
```

**Comment by sogaoh** [comment]
template.yml を１世代戻したところ deploy 成功するようになった
https://github.com/sogaoh/sam-book-sample/commit/deeb39b60e636c9a95eab571c1c852ddff5f2280

```
・・・
COMPOSE_PROJECT_NAME=sam-book-sample docker-compose -f docker-compose.yml run sam-local ./scripts/deploy.sh
upload: ./swagger.yml to s3://swagger-xxxxxxxxxxxxxxxxxxxx/swagger.yml
Uploading to 999ebac72fb68f0cdfd4fd83e2a6d7eb  5307846 / 5307846.0  (100.00%)
Successfully packaged artifacts and wrote output template to file ./packaged.yml.
Execute the following command to deploy the packaged template
aws cloudformation deploy --template-file /var/opt/src/sam-book-sample/packaged.yml --stack-name <YOUR STACK NAME>

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - sam-sample

~/src/temp/20190501/sam-book-sample practice-sogaoh* 5m 28s
```

**Comment by memememomo** [comment]
CloudFormationでのデプロイ処理中にエラーが起こっているようですね 🤔 
CloudFormationのエラー内容は、AWSコンソールで確認することができます。

`sam-sample` というスタック名をクリックすると、イベント情報でデプロイ状況が表示されると思います。

新コンソールの場合の表示。

<img width="1581" alt="スクリーンショット 2019-05-03 16 06 30" src="https://user-images.githubusercontent.com/174975/57123731-cbfb4780-6dbd-11e9-9277-f332708a0e07.png">


どのようなエラーが起こっているのか、ご確認いただけますでしょうか。

https://github.com/sogaoh/sam-book-sample/commit/deeb39b60e636c9a95eab571c1c852ddff5f2280#diff-63972137e7b062dcb093c1346d5ab08aL21
のバケット名が被ってしまっているのではないかと予測しているのですが... 🤔

**Comment by sogaoh** [comment]
> https://github.com/sogaoh/sam-book-sample/commit/deeb39b60e636c9a95eab571c1c852ddff5f2280#diff-63972137e7b062dcb093c1346d5ab08aL21
> のバケット名が被ってしまっているのではないかと予測しているのですが... 🤔

大いに、それのような気がします。
バケット名を .env から渡せるか、方法を探って試します。
ありがとうございます。 🙇

**Comment by sogaoh** [comment]
バケット名を .env から渡す方法にしてみて deploy しましたが、同様に 255 エラーで失敗しました。

AWSマネジメントコンソールを確認して、以下のエラーであることを把握したので対策を試みます。

|項目|内容|
|--|--|
|状況|CREATE_FAILED |
|タイプ|AWS::Events::Rule |
|論理ID|ScheduleHandlerCheckReservedPushNotification |
|状況の理由|Parameter  ScheduleExpression is not valid. <br>(Service: AmazonCloudWatchEvents;  <br>Status Code: 400; <br>Error Code: ValidationException; <br>Request ID:  486cc755-6db4-11e9-9774-55968fbb075f)|

**Comment by sogaoh** [comment]
原因判明。これもまた１文字 typo でした。。
https://github.com/sogaoh/sam-book-sample/blob/380d33411e1bd4b088c9569d9140130cb151bf52/template.yml#L405

バケット名の被りは当初はなく、逆に
https://github.com/sogaoh/sam-book-sample/blob/3bab1a32d0ccc7abcd1299c12219805f5b2066e6/template.yml#L21
の変更で被るようにしてしまっていました。。 

以下３点の成功を確認できたので、Closeします。
- デプロイの成功
- スケジュールイベントの発火
- S3イベントの発火
```
❯ aws s3 cp ./docker-compose.yml s3://sam-book-test/
upload: ./docker-compose.yml to s3://sam-book-test/docker-compose.yml
```
